#! /bin/sh
### BEGIN INIT INFO
# Provides:          wx-keyboard-tester
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Keyboard Testing program
# Description:       Starts keyboard tester, shuts-down when finished.
### END INIT INFO

# Do NOT "set -e"

# to set $SCRIPT, if you really must
if [ -f /etc/default/wx-keyboard-tester ]; then
    . /etc/default/wx-keyboard-tester
fi
if [ -z "$SCRIPT" -o ! -f "$SCRIPT" ]; then
    SCRIPT=/usr/bin/wx-keyboard-tester
fi
if [ ! -f $SCRIPT ]; then
    SCRIPT=/root/wxKeyboardTester/bin/keyboard.pl
fi
if [ ! -f $SCRIPT -a "$1" = "start" ]; then
    echo "Can't find keyboard.pl/wx-keyboard-tester"
    exit 1
fi

case "$1" in
  start)
	xinit $SCRIPT && shutdown -h now
	;;
  stop|restart|force-reload)
        echo "action $1 is not implemented."
        ;;
  *)
	echo "Usage: $SCRIPTNAME {start,stop,restart,force-reload}" >&2
	exit 3
	;;
esac

