#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/wx-keyboard-tester" ]; then
        update-rc.d wx-keyboard-tester defaults >/dev/null
fi
# no debhelper token, we don't want to start it on install.
